import React, { useState } from 'react';
import { SystemBadge } from './ui/SystemBadge';


export const SimulationLoop: React.FC = () => {
  const [selectedStep, setSelectedStep] = useState<number>(3);

  const steps = [
    {
      num: "01",
      title: "Proposed Change",
      desc: "Remediation plan or configuration update generated by AI or engineer."
    },
    {
      num: "02",
      title: "Static Validation",
      desc: "Syntax, schema, and configuration constraint verification against cloud specs."
    },
    {
      num: "03",
      title: "Security & Policy Check",
      desc: "Evaluates change against Open Policy Agent (OPA) guardrails and IAM least-privilege."
    },
    {
      num: "04",
      title: "Blast-Radius Analysis",
      desc: "Simulates traffic routing, downstream dependencies, and database load before touching live infra."
    },
    {
      num: "05",
      title: "Calculated Risk Score",
      desc: "Assigns objective risk grade with required approval hierarchy."
    }
  ];

  return (
    <section id="simulation" className="py-24 md:py-36 border-t border-[#1e2229] bg-[#08090a]">
      <div className="max-w-[1280px] mx-auto px-6 md:px-10">
        {/* Section Header */}
        <div className="max-w-3xl mb-16 md:mb-20">
          <span className="text-xs font-mono text-[#0ea5e9] tracking-wider uppercase block mb-3">
            04 / Pre-Flight Simulation Engine
          </span>
          <h2 className="text-3xl sm:text-5xl font-medium tracking-tight text-[#ededed] leading-tight mb-6">
            Before it acts, <br />
            <span className="text-[#888d96]">ArchViz models the impact.</span>
          </h2>
          <p className="text-base sm:text-lg text-[#888d96] leading-relaxed">
            AI should never blind-apply changes to production infrastructure. ArchViz evaluates every proposed action in a simulated digital twin before generating an execution plan.
          </p>
        </div>

        {/* 5-Step Pipeline Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-10">
          {steps.map((step, idx) => (
            <button
              key={idx}
              onClick={() => setSelectedStep(idx)}
              className={`p-4 rounded text-left transition-all font-mono text-xs ${
                selectedStep === idx
                  ? 'bg-[#0e1013] border border-[#0ea5e9] text-[#ededed] shadow-lg'
                  : 'bg-[#0a0b10] border border-[#1e2229] text-[#888d96] hover:border-[#2e3440] hover:text-[#ededed]'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] text-[#5e636e]">{step.num}</span>
                {selectedStep === idx && <span className="w-1.5 h-1.5 rounded-full bg-[#0ea5e9]" />}
              </div>
              <h4 className="font-semibold text-sm mb-1.5 text-[#ededed]">{step.title}</h4>
              <p className="text-[11px] font-sans text-[#888d96] leading-relaxed">{step.desc}</p>
            </button>
          ))}
        </div>

        {/* Step Deep-Dive Canvas Box */}
        <div className="p-6 md:p-8 rounded-lg bg-[#0e1013] border border-[#1e2229] shadow-xl">
          <div className="flex items-center justify-between pb-4 mb-6 border-b border-[#1e2229] text-xs font-mono">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-[#10b981]" />
              <span className="text-[#ededed]">SIMULATION RUNNER: STEP {selectedStep + 1} OF 5</span>
            </div>
            <SystemBadge status="healthy" label="Pre-flight Passed" />
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-6 space-y-4">
              <h3 className="text-xl font-medium text-[#ededed]">
                {steps[selectedStep].title}
              </h3>
              <p className="text-sm text-[#888d96] leading-relaxed">
                {steps[selectedStep].desc}
              </p>

              <div className="space-y-2 pt-2 text-xs font-mono">
                <div className="p-3 rounded bg-[#08090a] border border-[#1e2229] flex items-center justify-between">
                  <span className="text-[#888d96]">Affected Target Nodes</span>
                  <span className="text-[#ededed] font-medium">1 service (svc-checkout-prod)</span>
                </div>
                <div className="p-3 rounded bg-[#08090a] border border-[#1e2229] flex items-center justify-between">
                  <span className="text-[#888d96]">Estimated Downtime</span>
                  <span className="text-[#10b981] font-medium">0 ms (Zero-downtime blue/green roll)</span>
                </div>
                <div className="p-3 rounded bg-[#08090a] border border-[#1e2229] flex items-center justify-between">
                  <span className="text-[#888d96]">Calculated Risk Score</span>
                  <span className="text-[#10b981] font-medium">LOW (Grade A - 0.04 risk rating)</span>
                </div>
              </div>
            </div>

            <div className="lg:col-span-6">
              <div className="p-4 rounded bg-[#08090a] border border-[#1e2229] font-mono text-xs">
                <div className="text-[#5e636e] pb-2 mb-2 border-b border-[#1e2229] flex items-center justify-between">
                  <span>simulated_diff.tfplan</span>
                  <span className="text-[#10b981]">0 breaking changes</span>
                </div>
                <pre className="text-[11px] leading-relaxed text-[#888d96] overflow-x-auto">
{`~ resource "aws_ecs_service" "checkout_prod" {
    ~ task_definition = "arn:aws:...:task/v43" -> "arn:aws:...:task/v42"
    ~ desired_count   = 8 -> 8 (healthy targets verified)
  }

# Blast-radius graph check:
# -> Dependency 'aurora-pg-primary' pool release: +375 handles
# -> Dependency 'alb-edge-v2' healthcheck route: 200 OK
# -> OPA Policy Check: PASS (Rule: no-downtime-prod-deploy)`}
                </pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
